        <script src="PERCH_LOGINPATH/addons/plugins/editors/markitup/jquery.markitup.js"></script>
        <script src="PERCH_LOGINPATH/addons/plugins/editors/markitup/config.js"></script>
        <script src="PERCH_LOGINPATH/addons/plugins/editors/markitup/image_upload/image_upload.js"></script>
        <script src="PERCH_LOGINPATH/core/assets/js/jquery.form.min.js"></script>
        <link rel="stylesheet" href="PERCH_LOGINPATH/addons/plugins/editors/markitup/css/markitup.min.css" />
