<?php
	include(__DIR__.'/../lib/PerchRunway.class.php');
	include(__DIR__.'/../lib/PerchConfig.class.php');
	include(__DIR__.'/../lib/PerchRouter.class.php');
	include(__DIR__.'/../lib/PerchRoutedPage.class.php');
	include(__DIR__.'/../lib/PerchPageRoutes.class.php');
	include(__DIR__.'/../lib/PerchPageRoute.class.php');
	include(__DIR__.'/../lib/PerchAdminSearch.class.php');
	include(__DIR__.'/../lib/vendor/autoload.php');