<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'OpenStack\\Tests\\' => array($vendorDir . '/openstack/openstack-sdk-php/tests/Tests'),
    'OpenStack\\' => array($vendorDir . '/openstack/openstack-sdk-php/src/OpenStack'),
    'GuzzleHttp\\Stream\\' => array($vendorDir . '/guzzlehttp/streams/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
);
