name: Tag release from main
on:
  push:
    branches: [main]
    paths:
      - package.json
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Read version from package.json
        id: ver
        run: |
          VER=$(node -p "require('./package.json').version")
          echo "ver=$VER" >> "$GITHUB_OUTPUT"

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create tag if missing
        run: |
          if git rev-parse "refs/tags/${{ steps.ver.outputs.ver }}" >/dev/null 2>&1; then
            echo "Tag exists; skipping"
          else
            git tag -a "${{ steps.ver.outputs.ver }}" -m "Release ${{ steps.ver.outputs.ver }}"
            git push origin "${{ steps.ver.outputs.ver }}"
          fi
